-- Minimal usage/analytics support for the Venom GPT admin console
create table if not exists public.usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  event_name text not null,
  feature text,
  duration_ms bigint,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.usage_events enable row level security;

create policy "users can insert usage events"
  on public.usage_events for insert
  to anon, authenticated
  with check (true);
