create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  plan text not null default 'free' check (plan in ('free','pro')),
  role text not null default 'user' check (role in ('user','owner','admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.newsletter_subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique,
  status text not null default 'subscribed' check (status in ('subscribed','unsubscribed','pending')),
  source text,
  created_at timestamptz not null default now(),
  unsubscribed_at timestamptz
);

create table if not exists public.app_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  event_name text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- VenomGPT long-term memory. Only the authenticated owner can read/write their memories.
create table if not exists public.memories (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  memory text not null check (char_length(trim(memory)) between 1 and 500),
  category text not null default 'general',
  source text not null default 'user',
  importance smallint not null default 3 check (importance between 1 and 5),
  archived boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists memories_user_active_idx on public.memories(user_id, archived, created_at desc);

alter table public.profiles enable row level security;
alter table public.newsletter_subscribers enable row level security;
alter table public.app_events enable row level security;
alter table public.memories enable row level security;

create policy "users can read their own profile"
  on public.profiles for select
  using (auth.uid() = id);

create policy "users can update their own profile"
  on public.profiles for update
  using (auth.uid() = id);

create policy "public can subscribe to newsletter"
  on public.newsletter_subscribers for insert
  to anon, authenticated
  with check (true);

create policy "public can track anonymous app events"
  on public.app_events for insert
  to anon, authenticated
  with check (true);

create policy "users can read their own memories"
  on public.memories for select
  to authenticated
  using (auth.uid() = user_id);

create policy "users can create their own memories"
  on public.memories for insert
  to authenticated
  with check (auth.uid() = user_id);

create policy "users can archive their own memories"
  on public.memories for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
