create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  plan text not null default 'free' check (plan in ('free','pro')),
  role text not null default 'user' check (role in ('user','owner','admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.newsletter_subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique,
  status text not null default 'subscribed' check (status in ('subscribed','unsubscribed','pending')),
  source text,
  created_at timestamptz not null default now(),
  unsubscribed_at timestamptz
);

create table if not exists public.app_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  event_name text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.newsletter_subscribers enable row level security;
alter table public.app_events enable row level security;

create policy "users can read their own profile"
  on public.profiles for select
  using (auth.uid() = id);

create policy "users can update their own profile"
  on public.profiles for update
  using (auth.uid() = id);

create policy "public can subscribe to newsletter"
  on public.newsletter_subscribers for insert
  to anon, authenticated
  with check (true);

create policy "public can track anonymous app events"
  on public.app_events for insert
  to anon, authenticated
  with check (true);
